### ISSUE TITLE
Cannot `vagrant up` on Ubuntu 14.04

### ISSUE THREAD

**Issue by amingilani** [litaio/development-environment#5]
Ran into this

```
 gilani@debris: vagrant up
/usr/share/vagrant/plugins/provisioners/docker/plugin.rb:13:in `require_relative': /usr/share/vagrant/plugins/provisioners/docker/config.rb:23: syntax error, unexpected tPOW (SyntaxError)
      def run(name, **options)
                      ^
/usr/share/vagrant/plugins/provisioners/docker/config.rb:43: syntax error, unexpected keyword_end, expecting $end
    from /usr/share/vagrant/plugins/provisioners/docker/plugin.rb:13:in `block in <class:Plugin>'
    from /usr/lib/ruby/vendor_ruby/vagrant/registry.rb:27:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/registry.rb:27:in `get'
    from /usr/share/vagrant/plugins/kernel_v2/config/vm_provisioner.rb:34:in `initialize'
    from /usr/share/vagrant/plugins/kernel_v2/config/vm.rb:223:in `new'
    from /usr/share/vagrant/plugins/kernel_v2/config/vm.rb:223:in `provision'
    from /home/gilani/Sandbox/lita-dev/Vagrantfile:60:in `block in <top (required)>'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/loader.rb:37:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/loader.rb:37:in `load'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:104:in `block (2 levels) in load'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:98:in `each'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:98:in `block in load'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:95:in `each'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:95:in `load'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:265:in `config_global'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:519:in `block in action_runner'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:36:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:36:in `run'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:283:in `hook'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:139:in `initialize'
    from /usr/bin/vagrant:105:in `new'
    from /usr/bin/vagrant:105:in `<main>'
```

**Comment by jimmycuadra** [comment]
Looks like you installed Vagrant with a system package instead of via the official installer from https://www.vagrantup.com/. I believe the official installer is the only supported method. Whatever version you are using is packaged with a version of Ruby older than 2.0.

**Comment by amingilani** [comment]
I see, thanks @jimmycuadra. I'm download the official .deb right now. Will update this thread.

**Comment by jimmycuadra** [comment]
It's also worth noting that if you already have a development environment on your Ubuntu system, you don't really need the Lita development environment at all. It's just supposed to be a self contained system for people who are very new to programming or to Ruby.

**Comment by amingilani** [comment]
That makes sense, but I just wanted to try it out. I'm kinda new to Ruby myself :)

I ran into another error:

```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'coreos-stable' is up to date...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
```

**Comment by jimmycuadra** [comment]
Hard to say without more information. Usually oddities with the VMs can be resolved by restarting your computer. As horrible as that is, that's pretty much the state of virtual machine software these days.

**Comment by dkakollu** [comment]
Faced same issue on Ubuntu 14.04 and vagrant vagrant_1.4.3, after update to vagrant_1.8.1 its working fine for me....

**Comment by kjata30** [comment]
Make sure VT-X Virtualization is enabled in your BIOS.
