### ISSUE TITLE
Make sure Git is installed

### ISSUE THREAD

**Issue by jimmycuadra** [litaio/development-environment#6]
Moved from https://github.com/litaio/lita/issues/189.

---

If I follow the documentation between https://docs.lita.io/getting-started/installation/#development-environment and https://docs.lita.io/plugin-authoring/handlers/

The result is:

```
lita@4ac79d5e8890:~/workspace/lita$ lita handler hello
/home/lita/.gems/gems/lita-4.7.0/lib/lita/cli.rb:153:in ``': No such file or directory - git (Errno::ENOENT)
        from /home/lita/.gems/gems/lita-4.7.0/lib/lita/cli.rb:153:in `generate_user_config'
        from /home/lita/.gems/gems/lita-4.7.0/lib/lita/cli.rb:149:in `generate_config'
        from /home/lita/.gems/gems/lita-4.7.0/lib/lita/cli.rb:103:in `handler'
        from /home/lita/.gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/lita/.gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/lita/.gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/lita/.gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/lita/.gems/gems/lita-4.7.0/bin/lita:6:in `<top (required)>'
        from /home/lita/.gems/bin/lita:22:in `load'
        from /home/lita/.gems/bin/lita:22:in `<main>'
```

2 fixes need to be done:
- check if the git command is there before trying to invoke it and give a user friendly error
- add git in the lita docker image so it doesn't happen

The workaround of course:

```
lita@4ac79d5e8890:~/workspace/lita$ sudo apt-get install git
```

**Comment by mbbroberg** [comment]
Ran into the same issue and I was so focused on building a handler I didn't realize it had to do with git. Thanks for posting this @jimmycuadra.

**Comment by bladedshard** [comment]
I have the same issue.  So far no fix.
```
 The exception was:
undefined method `example_chat_service' for #<Lita::Configuration:0x00000001120d08>
Full backtrace:
/home/bots/lita/lita_config.rb:6:in `block in <top (required)>'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/registry.rb:17:in `configure'
/home/bots/lita/lita_config.rb:1:in `<top (required)>'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/configuration_builder.rb:49:in `load'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/configuration_builder.rb:49:in `load_user_config'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita.rb:75:in `run'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/cli.rb:77:in `start'
/var/lib/gems/2.1.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.1.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.1.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/var/lib/gems/2.1.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/var/lib/gems/2.1.0/gems/lita-4.7.1/bin/lita:6:in `<top (required)>'
/usr/local/bin/lita:22:in `load'
/usr/local/bin/lita:22:in `<main>'
```

My config as a test is taken directly from the lita website


```
Lita.configure do |config|
  config.robot.name = "Sir Bottington"
  config.robot.mention_name = "bottington"
  config.robot.alias = "/"
  config.robot.adapter = :irc
  config.adapters.example_chat_service.username = "bottington"
  config.adapters.example_chat_service.password = "secret"
 ## config.redis[:host] = "redis.example.com"
  config.handlers.karma.cooldown = 300
  config.handlers.google_images.safe_search = :off
end

```



The irc chat is no help.

**Comment by bladedshard** [comment]
Still no good.

Config is as follows 



```
Lita.configure do |config|
  config.robot.name = "Lita"
  config.robot.mention_name = "lita"
  config.robot.adapter = :irc
  config.adapters.irc.server = "irc.forestofone.com"
  config.adapters.irc.channels = ["#main"]
  config.adapters.irc.user = "Lita"
  config.adapters.irc.password = "secret"
  config.adapters.irc.realname = "Lita"
#  config.redis[:host] = "127.0.0.1"
#  config.redis[:port] = "6379"
  config.adapters.irc.cinch = lambda do |cinch_config|
    cinch_config.max_reconnect_delay = 123
end
        end
```

When I type lita 
It just stay at 
[2017-01-24 22:26:54 UTC] INFO: Connecting to IRC.  

But doesn't connect to my irc server.

**Comment by jimmycuadra** [comment]
@bladedshard The problems you are having are not related to this issue. We can continue to discuss in IRC, or you should open a new issue. Thanks!
