### ISSUE TITLE
trying to create a new adapter

### ISSUE THREAD

**Issue by cpanato** [litaio/development-environment#7]
Hello 
Im trying to create a new adapter but when run the command `lita adapter blalba` it returns:

what I'm doing wrong? I'm following the steps on the documentation

thanks

```
CoreOS stable (1185.5.0)
core@lita-dev ~ $ lita-dev
lita@043cc961f6be:~/workspace$ lita adapter lita-blabla
/home/lita/.gems/gems/lita-4.7.1/lib/lita/cli.rb:153:in ``': No such file or directory - git (Errno::ENOENT)
        from /home/lita/.gems/gems/lita-4.7.1/lib/lita/cli.rb:153:in `generate_user_config'
        from /home/lita/.gems/gems/lita-4.7.1/lib/lita/cli.rb:149:in `generate_config'
        from /home/lita/.gems/gems/lita-4.7.1/lib/lita/cli.rb:93:in `adapter'
        from /home/lita/.gems/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/lita/.gems/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/lita/.gems/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/lita/.gems/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /home/lita/.gems/gems/lita-4.7.1/bin/lita:6:in `<top (required)>'
        from /home/lita/.gems/bin/lita:22:in `load'
        from /home/lita/.gems/bin/lita:22:in `<main>'
```

**Comment by jimmycuadra** [comment]
Sorry for the trouble! You need to install Git manually right now. See #6.
